Improve code quality 2
lovettchris/SgmlReader pull request #9
Opened 2021-01-31 07:36 UTC by iamcarbon

This PR has no functional changes and is focused on improving code quality / consistency.

2021-01-31 22:52 UTC, lovettchris requested changes
Thanks, I'm generally not a fan of removing "this." and I'm not a huge fan of adopting the latest language 9 features just because.  But you have a lot of other good stuff in here.  But the one open issue on replacing => m_contentModel with {get;} why was that change made?

2021-01-31 22:52 UTC, lovettchris commented on SgmlReaderDll/SgmlParser.cs
> -        public ContentModel ContentModel => m_contentModel;
Why did you change this?  => m_contentModel is the now recommended way of exposing read only properties on a private member variable.

2021-02-02 16:48 UTC, iamcarbon commented
@lovettchris 

Agreed on removing the readonly auto-implemented properties. 

After removing the m_ prefix from the private variables, this felt redundant and out of place. This is likely from having spent a lot of time with the core runtime libraries which standardized on a naked without a prefix. Here is the runtime library conventions. Notable are rules 3 (Prefix internal and private instance fields with _) and 4 (We avoid this. unless absolutely necessary.).

https://github.com/dotnet/runtime/blob/10381a2cdc33860f0dc649b24cbb703d23b9ea33/docs/coding-guidelines/coding-style.md

Happy to prefix them again if you prefer. 

The C# 9 pattern matching features do aid in readability, particularly when used in switch expressions. Let me know if you think these pattern uses should be reverted.

2021-02-02 18:30 UTC, lovettchris commented on SgmlReaderDll/SgmlParser.cs
> -        public ContentModel ContentModel => m_contentModel;
thanks.

2021-02-02 18:32 UTC, lovettchris commented
No need to revert anything, it looks good now.

2021-02-02 18:35 UTC, merged

2021-02-02 20:12 UTC, lovettchris commented
Published: https://www.nuget.org/packages/Microsoft.Xml.SgmlReader/1.8.20